version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
    - graphviz
    - inkscape
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-latex-extra

sphinx:
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: doc/sphinx/requirements.txt

formats:
  - pdf
  - epub 