function deprecatedBoundaryWrapperWarning(wrapperName, replacementName)
    warning([wrapperName ':Deprecated'], ...
            ['' wrapperName ' is deprecated. Use ' replacementName ' directly for ' ...
             'boundary-condition application.']);
end