name: Julia Documentation

on:
  pull_request:
  push:
    branches:
      - main
    tags: '*'

permissions:
  contents: write
  pull-requests: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docbuild:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - uses: julia-actions/setup-julia@v3
        with:
          version: '1.10'

      - uses: julia-actions/cache@v3

      - name: Install dependencies
        run: >
          cd julia/MOLE.jl &&
          julia --project=docs -e 'using Pkg;
          Pkg.develop(path=".");
          Pkg.instantiate(; verbose=true);
          Pkg.build()'

      - name: Build and deploy
        env:
          GKSwstype: "100" # Headless GR backend
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: >
          cd julia/MOLE.jl &&
          julia --project=docs docs/make.jl